#!/usr/bin/env node
/*
 * generate-compat — data/compat.json, the ecosystem compatibility record.
 *
 * Three things in the abap2UI5 ecosystem carry a version, and each is pinned
 * on its own: the framework release an app runs on (app-template pins it,
 * 1.144.0 today), the linter version an app installs (`@abap2ui5/linter` in
 * its package.json), and the UI5 version the linter's metadata snapshot was
 * generated at (`ui5Version` in data/properties.json). Nothing said which
 * framework releases a given linter line actually understands - the rules
 * assume a client API (`z2ui5_cl_ui5_view_builder`, `client->get_event( )`)
 * that an older framework does not have, and the hand-maintained mirrors in
 * lib/ (frontend-actions, formatters, released-api, cc-controls, the cs_event
 * fixture) are synced against ONE upstream state. This file says so, and it
 * ships with the package (`./compat` in the exports map, `data/` in files[]),
 * so app-template's check-pin, a doctor command or the VS Code extension can
 * read it instead of guessing.
 *
 *   node scripts/generate-compat.mjs                   write the file
 *   node scripts/generate-compat.mjs --local <dir>     also read an abap2UI5
 *                                                      checkout: its
 *                                                      package.json version
 *                                                      becomes framework.mirrored
 *   node scripts/generate-compat.mjs --check           exit 1 if the committed
 *                                                      file is stale (the test
 *                                                      uses this)
 *
 * What is derived and what is decided:
 *   linter              package.json version - derived, so a release bump
 *                       regenerates it (npm test fails while it is stale)
 *   framework.minimum   DECIDED here (FRAMEWORK_MINIMUM): the oldest release
 *                       whose client API the rules assume
 *   framework.mirrored  the abap2UI5 version the mirrors were last synced
 *                       against - read from `--local`, else kept from the
 *                       committed file (an offline regeneration must not
 *                       forget it)
 *   ui5.floor           the default `minUi5` the gate judges against
 *   ui5.snapshot        data/properties.json's ui5Version - derived
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
export const COMPAT_FILE = path.join(ROOT, 'data', 'compat.json');

/* The oldest framework release whose released client API the rules assume.
 * 1.142.0 has neither `z2ui5_cl_ui5_view_builder` (the builder every view
 * rule reconstructs) nor `client->get_event( )` (what `event-without-handler`
 * and the lifecycle rules read), so an app on it is not one this linter can
 * judge; 1.144.0 is the first release that has both, and it is the floor
 * app-template pins for the same reason. Raise it when a rule starts to
 * assume something newer, and say which rule in the CHANGELOG. */
export const FRAMEWORK_MINIMUM = '1.144.0';

/* The default `minUi5` (lib/index.mjs DEFAULTS, the `--ui5` flag): abap2UI5's
 * own OpenUI5 floor. The gate's knowledge runs from here to the snapshot. */
export const UI5_FLOOR = '1.71';

export const SEMVER = /^\d+\.\d+\.\d+$/;

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));

/** The `framework.mirrored` the committed file carries, or null before the first generation. */
export function committedMirrored() {
  if (!fs.existsSync(COMPAT_FILE)) return null;
  try { return readJson(COMPAT_FILE).framework?.mirrored ?? null; } catch { return null; }
}

/** The version of an abap2UI5 checkout, from its package.json. */
export function localFrameworkVersion(dir) {
  const manifest = path.join(dir, 'package.json');
  const { version } = readJson(manifest);
  if (!SEMVER.test(version ?? '')) throw new Error(`${manifest}: version '${version}' is not a release number`);
  return version;
}

export function buildCompat({ mirrored = committedMirrored() ?? FRAMEWORK_MINIMUM } = {}) {
  const { version: linter } = readJson(path.join(ROOT, 'package.json'));
  const { ui5Version: snapshot } = readJson(path.join(ROOT, 'data', 'properties.json'));
  return {
    note: 'The ecosystem compatibility record of @abap2ui5/linter, generated by scripts/generate-compat.mjs (npm run generate-compat) and gated by npm test - never hand-edit. '
      + '"linter" is this package\'s version. "framework.minimum" is the oldest abap2UI5 release whose released client API the rules assume (z2ui5_cl_ui5_view_builder, client->get_event( )) - an app on an older release is not one this linter can judge. '
      + '"framework.mirrored" is the abap2UI5 release the hand-maintained mirrors in lib/ (frontend-actions, formatters, released-api, cc-controls, the cs_event fixture) were last synced against - a newer framework may have wires or objects the linter does not know yet (scripts/check-upstream.mjs reports that drift). '
      + '"ui5.floor" is the default UI5 version the gate judges against (--ui5), "ui5.snapshot" the version the metadata snapshot in data/properties.json was generated at - the gate knows nothing newer. '
      + 'Read it through the package exports map as @abap2ui5/linter/compat: app-template\'s check-pin and doctor scripts compare their framework pin against it, the VS Code extension reads it to say which framework line a bundled linter understands. '
      + 'Regenerated on every linter release (the version), on a mirror sync (npm run generate-compat -- --local <abap2UI5 checkout>) and on a snapshot bump.',
    linter,
    framework: { minimum: FRAMEWORK_MINIMUM, mirrored },
    ui5: { floor: UI5_FLOOR, snapshot },
  };
}

export const render = (opts) => `${JSON.stringify(buildCompat(opts), null, 2)}\n`;

const invokedDirectly = process.argv[1] && fs.realpathSync(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  const localAt = process.argv.indexOf('--local');
  const local = localAt !== -1 ? process.argv[localAt + 1] : null;
  if (localAt !== -1 && !local) {
    console.error('generate-compat: --local needs the path of an abap2UI5 checkout');
    process.exit(2);
  }
  let mirrored;
  try {
    mirrored = local ? localFrameworkVersion(local) : undefined;
  } catch (e) {
    console.error(`generate-compat: ${e.message}`);
    process.exit(2);
  }
  const text = render({ ...(mirrored ? { mirrored } : {}) });
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(COMPAT_FILE) ? fs.readFileSync(COMPAT_FILE, 'utf8') : '';
    if (current !== text) {
      console.error('data/compat.json is stale — run: npm run generate-compat');
      process.exit(1);
    }
    console.log('data/compat.json is up to date');
  } else {
    fs.writeFileSync(COMPAT_FILE, text);
    const c = buildCompat({ ...(mirrored ? { mirrored } : {}) });
    console.log(`wrote ${path.relative(ROOT, COMPAT_FILE)} (linter ${c.linter}, framework ${c.framework.minimum} minimum / ${c.framework.mirrored} mirrored, UI5 ${c.ui5.floor}-${c.ui5.snapshot})`);
  }
}
